# Generated by Django 2.2.12 on 2020-04-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conlang',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
