# Generated by Django 2.2.12 on 2020-04-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conlang_creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conlang',
            old_name='user_id',
            new_name='user',
        ),
    ]
