# Generated by Django 2.2.12 on 2020-04-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonology', '0001_initial'),
        ('conlang_creator', '0002_auto_20200426_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='conlang',
            name='consonants',
            field=models.ManyToManyField(to='phonology.Consonant'),
        ),
        migrations.AddField(
            model_name='conlang',
            name='vowels',
            field=models.ManyToManyField(to='phonology.Vowel'),
        ),
    ]
