# Generated by Django 2.2.12 on 2020-05-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conlang_creator', '0003_auto_20200426_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='conlang',
            name='syllable_structure',
            field=models.CharField(default='CV', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conlang',
            name='word_structure',
            field=models.CharField(default='O', max_length=20),
            preserve_default=False,
        ),
    ]
