# Generated by Django 2.2.12 on 2020-05-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conlang_creator', '0004_auto_20200506_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conlang',
            name='consonants',
        ),
        migrations.AddField(
            model_name='conlang',
            name='consonants',
            field=models.CharField(default='p t k', max_length=300),
        ),
        migrations.RemoveField(
            model_name='conlang',
            name='vowels',
        ),
        migrations.AddField(
            model_name='conlang',
            name='vowels',
            field=models.CharField(default='a i u', max_length=200),
        ),
    ]
