# Generated by Django 2.2.12 on 2020-04-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Manner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Roundedness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='VowelHorizontalPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='VowelVerticalPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vowel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa', models.CharField(max_length=5)),
                ('horizontal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonology.VowelHorizontalPosition')),
                ('length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonology.Length')),
                ('roundedness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonology.Roundedness')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonology.VowelVerticalPosition')),
            ],
        ),
        migrations.CreateModel(
            name='Consonant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa', models.CharField(max_length=5)),
                ('manner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonology.Manner')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonology.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Affricate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa', models.CharField(max_length=5)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonology.Feature')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affricate_first_element', to='phonology.Consonant')),
                ('manner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonology.Manner')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affricate_second_element', to='phonology.Consonant')),
            ],
        ),
    ]
