# Generated by Django 2.2.12 on 2020-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consonant',
            name='features',
            field=models.ManyToManyField(to='phonology.Feature'),
        ),
    ]
